import type { NavSection } from '@/types';

export const navigation: NavSection[] = [
  {
    id: 'top',
    label: '',
    labelEn: '',
    items: [
      {
        id: 'dashboard',
        label: '仪表盘',
        labelEn: 'Dashboard',
        icon: 'LayoutDashboard',
        path: '/',
      },
      {
        id: 'approvals',
        label: '审批收件箱',
        labelEn: 'Approval Inbox',
        icon: 'CheckCircle2',
        path: '/approvals',
      },
    ],
  },
  {
    id: 'procurement',
    label: '采购',
    labelEn: 'Procurement',
    items: [
      {
        id: 'pr-list',
        label: '采购申请',
        labelEn: 'PR List',
        icon: 'FileText',
        path: '/procurement/purchase-requisitions',
      },
      {
        id: 'po-list',
        label: '采购订单',
        labelEn: 'PO List',
        icon: 'ClipboardList',
        path: '/procurement/purchase-orders',
      },
      {
        id: 'rfq',
        label: '询价单',
        labelEn: 'RFQ',
        icon: 'FileSearch',
        path: '/procurement/rfq',
      },
      {
        id: 'goods-receipts',
        label: '收货单',
        labelEn: 'Goods Receipt',
        icon: 'PackageCheck',
        path: '/procurement/goods-receipts',
      },
      {
        id: 'goods-returns',
        label: '退货单',
        labelEn: 'Goods Return',
        icon: 'Undo2',
        path: '/procurement/goods-returns',
      },
    ],
  },
  {
    id: 'inventory',
    label: '库存',
    labelEn: 'Inventory',
    items: [
      {
        id: 'stock-overview',
        label: '库存总览',
        labelEn: 'Stock Overview',
        icon: 'Package',
        path: '/inventory/stock',
      },
      {
        id: 'material-issue-notices',
        label: '發料',
        labelEn: 'Material Withdrawal Confirmation',
        icon: 'PackageMinus',
        path: '/inventory/material-issue-notices',
      },
      {
        id: 'material-issue-requests',
        label: '領料',
        labelEn: 'Material Withdrawal Request',
        icon: 'PackageX',
        path: '/inventory/material-issue-requests',
      },
      {
        id: 'stock-transfers',
        label: '库存调拨',
        labelEn: 'Stock Transfers',
        icon: 'ArrowLeftRight',
        path: '/inventory/transfers',
      },
      {
        id: 'cycle-counts',
        label: '循环盘点',
        labelEn: 'Cycle Count',
        icon: 'ClipboardCheck',
        path: '/inventory/cycle-counts',
      },
      {
        id: 'safety-stock-alerts',
        label: '安全库存预警',
        labelEn: 'Safety Stock',
        icon: 'AlertTriangle',
        path: '/inventory/safety-stock-alerts',
      },
    ],
  },
  {
    id: 'manufacturing',
    label: '制造',
    labelEn: 'Manufacturing',
    items: [
      {
        id: 'work-orders',
        label: '生产批工单',
        labelEn: 'Build Orders',
        icon: 'Factory',
        path: '/manufacturing/work-orders',
      },
      {
        id: 'subcontract-orders',
        label: '委外加工',
        labelEn: 'Subcontract',
        icon: 'Truck',
        path: '/manufacturing/subcontract-orders',
      },
      {
        id: 'production-progress',
        label: '生产进度',
        labelEn: 'Production Progress',
        icon: 'BarChart3',
        path: '/manufacturing/production-progress',
      },
    ],
  },
  {
    id: 'engineering',
    label: '工程',
    labelEn: 'Engineering',
    items: [
      {
        id: 'item-master',
        label: '物料主数据',
        labelEn: 'Item Master',
        icon: 'Database',
        path: '/engineering/items',
      },
      {
        id: 'bom',
        label: 'BOM',
        labelEn: 'BOM',
        icon: 'Network',
        path: '/engineering/bom',
      },
      {
        id: 'bom-comparison',
        label: 'BOM 对比',
        labelEn: 'BOM Comparison',
        icon: 'GitCompareArrows',
        path: '/engineering/bom/comparison',
      },
      {
        id: 'ecr-eco',
        label: '工程变更',
        labelEn: 'ECR/ECO',
        icon: 'GitBranch',
        path: '/engineering/ecr',
      },
      {
        id: 'documents',
        label: '文档管理',
        labelEn: 'Documents',
        icon: 'FileBox',
        path: '/engineering/documents',
      },
    ],
  },
  {
    id: 'quality',
    label: '质量',
    labelEn: 'Quality',
    items: [
      {
        id: 'inspections',
        label: '检验',
        labelEn: 'Inspections',
        icon: 'ShieldCheck',
        path: '/quality/inspections',
      },
      {
        id: 'complaints',
        label: '客诉',
        labelEn: 'Complaints',
        icon: 'MessageSquareWarning',
        path: '/quality/complaints',
      },
      {
        id: 'nonconformance',
        label: 'NC/CAPA',
        labelEn: 'NC/CAPA',
        icon: 'AlertOctagon',
        path: '/quality/nonconformance',
      },
      {
        id: 'internal-qc',
        label: '内部检验',
        labelEn: 'Internal QC',
        icon: 'ClipboardCheck',
        path: '/quality/internal-qc',
      },
      {
        id: 'traceability',
        label: '追溯',
        labelEn: 'Traceability',
        icon: 'GitFork',
        path: '/quality/traceability',
      },
    ],
  },
  {
    id: 'sales',
    label: '订单管理',
    labelEn: 'Order Management',
    items: [
      {
        id: 'sales-orders',
        label: '订单总览',
        labelEn: 'Order Management',
        icon: 'ShoppingCart',
        path: '/sales/orders',
      },
      {
        id: 'sales-planning',
        label: '销售计划',
        labelEn: 'Sales Planning',
        icon: 'Calendar',
        path: '/sales/planning',
      },
      {
        id: 'sales-forecasts',
        label: '销售预测',
        labelEn: 'Forecasts',
        icon: 'TrendingUp',
        path: '/sales/forecasts',
      },
    ],
  },
  {
    id: 'finance',
    label: '财务',
    labelEn: 'Finance',
    items: [
      {
        id: 'costing',
        label: '成本核算',
        labelEn: 'Costing',
        icon: 'Calculator',
        path: '/finance/costing',
      },
      {
        id: 'payment-requests',
        label: '付款申请',
        labelEn: 'Payment Requests',
        icon: 'CreditCard',
        path: '/finance/payment-requests',
      },
      {
        id: 'ap-reconciliation',
        label: '应付对账',
        labelEn: 'AP Reconciliation',
        icon: 'Receipt',
        path: '/finance/ap-reconciliation',
      },
      {
        id: 'integration-status',
        label: '系统集成',
        labelEn: 'Integration',
        icon: 'Link',
        path: '/finance/integration-status',
      },
    ],
  },
  {
    id: 'reports',
    label: '报表',
    labelEn: 'Reports',
    items: [
      {
        id: 'reports-operational',
        label: '运营报表',
        labelEn: 'Operational',
        icon: 'BarChart3',
        path: '/reports/operational',
      },
      {
        id: 'reports-compliance',
        label: '合规报表',
        labelEn: 'Compliance',
        icon: 'Shield',
        path: '/reports/compliance',
      },
    ],
  },
  {
    id: 'admin',
    label: '系统管理',
    labelEn: 'Admin',
    items: [
      {
        id: 'admin-users',
        label: '用户与角色',
        labelEn: 'Users & Roles',
        icon: 'Users',
        path: '/admin/users',
      },
      {
        id: 'admin-approval-policies',
        label: '审批策略',
        labelEn: 'Approval Policies',
        icon: 'Settings2',
        path: '/admin/approval-policies',
      },
      {
        id: 'admin-custom-fields',
        label: '自定义字段',
        labelEn: 'Custom Fields',
        icon: 'Puzzle',
        path: '/admin/custom-fields',
      },
      {
        id: 'admin-system-config',
        label: '系统配置',
        labelEn: 'System Config',
        icon: 'Cog',
        path: '/admin/system-config',
      },
    ],
  },
];
